Wf = require('Libraries.windfield')
Sti = require('Libraries.sti')
World = Wf.newWorld(0, 0)
World:addCollisionClass("Transitions")
World:addCollisionClass("Button")
World:addCollisionClass("Zombie")
World:addCollisionClass("Eye")
World:addCollisionClass("Projectile")
Love = require('love')
Anim8 = require('Libraries.anim8')
Camera = require('Libraries.camera')
Player = require('Models.Player')
Bullets = require('Models.Bullet')
Zombies = require('Models.Zombie')
Eyes = require('Models.Eye')
require('src.loadMap')
require('src.Drawables')
require('src.Camera')
require('src.GenericFunctions')
require('src.Destroy')
